syntax = "proto3";

package remotezfs;

message ListPoolsRequest {}

message Pool {
    string name = 1;
}

message ListPoolsReply {
  repeated Pool pools = 1;
}

message PoolPropertyReply {
    string value = 1;
}

message PoolPropertyRequest {
    Pool target = 1;
    string property = 2;
}

service RemotePool {
    rpc ListPools(ListPoolsRequest) returns (ListPoolsReply) {}
    rpc getPoolProperty(PoolPropertyRequest) returns (PoolPropertyReply) {}
};


message Dataset {
    string name = 1;
}

message ListDatasetsRequest{
    string base = 1;
}

message ListDatasetsReply{
    repeated Dataset datasets = 1;
}

service RemoteDataset {
    rpc ListDatasets(ListDatasetsRequest) returns (ListDatasetsReply) {}
};
